[buildPlans.IosevkaNeudoerf]
family = "Iosevka Neudoerf"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.IosevkaNeudoerf.variants]
  inherits = "ss07"

    [buildPlans.IosevkaNeudoerf.variants.design]
    zero = "slashed"
