[buildPlans.iosevka-neudoerf]
family = "Iosevka Neudoerf"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.iosevka-neudoerf.variants]
  inherits = "ss07"

    [buildPlans.iosevka-neudoerf.variants.design]
    zero = "slashed"
