[buildPlans.IosevkaNeudoerf]
family = "Iosevka Neudoerf"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.IosevkaNeudoerf.variants]
  inherits = "ss05"

    [buildPlans.IosevkaNeudoerf.variants.design]
    two = "straight-neck-serifless"
    three = "flat-top-serifless"
    four = "semi-open-non-crossing-serifless"
    five = "oblique-arched-serifless"
    six = "straight-bar"
    zero = "slashed"
    a = "double-storey-toothless-corner"
    d = "toothless-corner-serifless"
    f = "serifless"
    g = "double-storey-open"
    i = "zshaped"
    j = "flat-hook-serifless"
    k = "cursive-serifless"
    l = "zshaped"
    m = "serifless"
    p = "eared-motion-serifed"
    q = "straight-motion-serifed"
    y = "cursive-flat-hook-serifless"
