[buildPlans.IosevkaNeudoerf]
family = "Iosevka Neudoerf"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaNeudoerf.variants.design]
two = "straight-neck-serifless"
three = "two-arcs"
four = "semi-open-non-crossing-serifless"
five = "oblique-arched-serifless"
six = "straight-bar"
zero = "slashed"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "serifless"
g = "double-storey-open"
i = "zshaped"
j = "flat-hook-serifless"
k = "cursive-serifless"
l = "zshaped"
m = "serifless"
p = "earless-corner-serifless"
q = "earless-corner-tailed-serifless"
r = "serifless"
w = "rounded-vertical-sides-serifless"
y = "cursive-flat-hook-serifless"
