"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch$git_status\
$nix_shell\
$time\
$line_break$character """

[os]
disabled = false
style = "fg:red"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:red"
style_root = "fg:red"
format = '[$user ]($style)'

[hostname]
ssh_only = false
format = '// [$hostname ](fg:yellow)'

[directory]
style = "fg:green"
format = "// [$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
style = "fg:cyan"
format = '// [$symbol $branch ]($style)'

[git_status]
style = "fg:cyan"
format = '[($all_status$ahead_behind )]($style)'

[nix_shell]
style = "fg:blue"
format = "// [$symbol $state ]($style)"
symbol = " "

[time]
disabled = false
time_format = "%R"
style = "fg:purple"
format = '// [  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
